<?php

namespace Louvre\TicketBundle\Repository;

use Doctrine\ORM\EntityRepository;
// N'oubliez pas ce use
use Doctrine\ORM\QueryBuilder;

/**
 * GlobalTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalTicketRepository extends \Doctrine\ORM\EntityRepository
{
	
}
