<?php

namespace Louvre\TicketBundle\Repository;

/**
 * GlobalTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
