<?php

namespace Louvre\TicketBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTicketsAtDate(\Datetime $date) {
		$qb = $this->createQueryBuilder('a');

		$qb
			->leftJoin('a.globalticket', 'g')
			->addSelect('g')
			
			->select("COUNT(a) AS nb")
		    ->where("g.datevisit = :date")
		    ->setParameter('date', $date)
		;

		return $qb
			->getQuery()	
			->getSingleResult()
			;
	}

	
}
