louvre_ticket_home:
    path:     /billetterie
    defaults: 
        _controller: LouvreTicketBundle:Ticketing:index


louvre_ticket_view:
    path:    /billetterie/{id}
    defaults:
        _controller: LouvreTicketBundle:Ticketing:view 

louvre_ticket_exemple:
    path:    /exemple
    defaults:
        _controller: LouvreTicketBundle:Ticketing:exemple 