louvre_ticket_home:
    path:     /billetterie
    defaults: 
        _controller: LouvreTicketBundle:Ticketing:index


louvre_ticket_view:
    path:    /billetterie/{id}
    defaults:
        _controller: LouvreTicketBundle:Ticketing:view 



louvre_ticket_charge:
    path:    /charge/{id}
    defaults:
        _controller: LouvreTicketBundle:Ticketing:charge

louvre_ticket_pdf:
    path:    /pdf/{id}
    defaults:
        _controller: LouvreTicketBundle:Ticketing:pdf