louvre_ticket_home:
    path:     /billetterie
    defaults: 
        _controller: LouvreTicketBundle:Ticketing:index


louvre_ticket_view:
    path:    /recapitulatif/{id}
    defaults:
        _controller: LouvreTicketBundle:Ticketing:view 



louvre_ticket_charge:
    path:    /charge/{id}
    defaults:
        _controller: LouvreTicketBundle:Ticketing:charge

louvre_ticket_confirm:
    path:    /confirm/{id}
    defaults:
        _controller: LouvreTicketBundle:Ticketing:confirm

louvre_ticket_test2:
    path:    /test2
    defaults:
        _controller: LouvreTicketBundle:Ticketing:test2

