services:
    louvre_ticket.pricer:
        class: Louvre\TicketBundle\Pricer\LouvrePricer

    louvre_ticket.validator.ticketlimit:                             
        class: Louvre\TicketBundle\Validator\TicketLimitValidator     
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"] 
        tags:
            - { name: validator.constraint_validator, alias: louvre_ticket_ticketlimit } 

    louvre_ticket.validator.holiday:                             
        class: Louvre\TicketBundle\Validator\HolidayValidator     
        arguments: 
            - "@request_stack"
            - "@doctrine.orm.entity_manager"
            - %holidays%
        tags:
            - { name: validator.constraint_validator, alias: louvre_ticket_holiday } 
    
    louvre_ticket.email.mailer:
      class: Louvre\TicketBundle\Email\Mailer
      arguments:
          - "@mailer"
         

    louvre_ticket.pdf.pdfbuilder:
      class: Louvre\TicketBundle\Pdf\PdfBuilder
      arguments:
          - "@doctrine.orm.entity_manager"
          - "@templating"
          - "@knp_snappy.pdf"
          

